### ISSUE TITLE
Configuration change request for CloudVeil 1.7.x

### ISSUE THREAD

**Issue by kfreezen** [cloudveiltech/FilterManager#109]
I'm currently working on splitting out configuration and rule lists so that we don't have to maintain thousands of different zip files for users.

Let me know if this requires a new API version so I can update CV4W accordingly.

### /api/v2/me/config/get
This will get the configuration JSON file for the currently authenticated user.

### /api/v2/me/config/check
This will return a checksum for the above-mentioned configuration file.

### /api/v2/rules/get
This will get a ZIP file of all rules available in the system.

### /api/v2/rules/check
This will return a checksum for the above-mentioned ZIP file.

All I want to do is take `cfg.json` out of the rule data file and create 4 new endpoints for it and the 'global' rule file.

**edit:** The checksum the client uses for verification is currently SHA1.

**Comment by bluesven869** [comment]
@kfreezen 
Can you  provide the **response** for each end point?

**Comment by dkwiebe** [comment]
@montesound I think we can close this.  Any comments?
