### ISSUE TITLE
More options in Platform for deployment options

### ISSUE THREAD

**Issue by kfreezen** [cloudveiltech/FilterManager#120]
Right now, the XML generator assumes a specific URL path and filename format for the update installers.
Example:
```
https://{url-host}/citadel/releases/win32/Citadel-{version}.msi
```
This won't work for mac and linux platforms because they won't be using msi's.

If nothing else, we need to allow the user to specify a filename format.

**Comment by bluesven869** [comment]
@kfreezen 

Can you post here exact url for linux or maxos version?

**Comment by kfreezen** [comment]
I don't have that yet. I don't think this needs to be done right at this moment as I marked it as `future`

**Comment by kfreezen** [comment]
Thinking about this a little bit more. What I'd really like is the ability to specify a file extension in the platform editor for the XML file generator to use. The update package extension might be `.sh` or `.installer` on linux and `.dmg` or `.pkg` or `.sh` on macOS.
