### ISSUE TITLE
Do not allow check-in days to be negative

### ISSUE THREAD

**Issue by kfreezen** [cloudveiltech/FilterManager#121]
I was able to save a negative "check-in days" in the Edit User Dialog.

**Comment by dkwiebe** [comment]
This is not fully patched yet.  The buttons in the web interface won't scroll below 0 but you can type in whatever number you want and then save it.

![image](https://user-images.githubusercontent.com/1034679/44304122-3ba0d380-a310-11e8-99bd-27fc3071b338.png)
