### ISSUE TITLE
No indicator to tell me when I need to select a group to clone

### ISSUE THREAD

**Issue by kfreezen** [cloudveiltech/FilterManager#123]
If I hit "Clone Group" without any group selected, nothing happens. It should popup a little alert in that case.

**Comment by bluesven869** [comment]
Actually, user didnot select group in the datatable, then"clone group" button will be disabled.
After disabled, user can't click that button.

is there any good idea to be user-friendly, @kfreezen ?

**Comment by kfreezen** [comment]
What you have there looks good to me.
