### ISSUE TITLE
apply_appgroup_to_usergroup 500 error

### ISSUE THREAD

**Issue by kfreezen** [cloudveiltech/FilterManager#125]
When I tried to apply app group to user group using the "Apply to User Group" button, I got a 500 error.

**Comment by bluesven869** [comment]
Hello, @kfreezen

Can you provide 500 error content for this issue?
In my localside, it working well. 

I guess, there is some differences between local environment & staging environment.

After checking the error, I am able to find what's wrong.

The best,

**Comment by dkwiebe** [comment]
@kfreezen I believe this has been patched. It appears to be working for me.  Can you confirm and then close it?

**Comment by kfreezen** [comment]
Can confirm, this works on my local machine.
