### ISSUE TITLE
New API call: /time

### ISSUE THREAD

**Issue by kfreezen** [cloudveiltech/FilterManager#128]
This one is fairly simple. All I need is a new API call for the client.

```
{
  "server_time": "2018-07-24T18:58:04Z"
}
```

The purpose of this API call is to allow us to verify that the client's time is actually correct. This will help prevent misuse of time restrictions.

**Comment by dkwiebe** [comment]
@kfreezen This exists on the test server under /api/user/time

![image](https://user-images.githubusercontent.com/1034679/44304180-ae5e7e80-a311-11e8-809a-85bea4f7b331.png)
