### ISSUE TITLE
Lists disappeared from the default group

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/FilterManager#25]
@dkwiebe Can you pull the logs on this?

**Comment by dkwiebe** [comment]
Just a couple of notes.  This is only happening on group 1.  It appears to be happening sometimes when a group is changed.

IP - - [25/Nov/2017:20:27:08 +0000] "PATCH /citadel/api/admin/groups/1 HTTP/1.1" 204 0 "https://manage.cloudveil.org/citadel/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
IP -  - [25/Nov/2017:20:27:08 +0000] "GET /citadel/api/admin/groups?_=1511641610627 HTTP/1.1" 200 172465 "https://manage.cloudveil.org/citadel/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"


/*==================================================*/
/* Query 3 - 2017-11-25 20:27:08 [1.7ms]  */
update `groups` set `id` = '1', `name` = 'Default', `isactive` = '1', `app_cfg` = '{"UpdateFrequency":10,"PrimaryDns":"198.58.111.139","SecondaryDns":"8.8.8.8","CannotTerminate":false,"BlockInternet":false,"UseThreshold":false,"ThresholdLimit":3,"ThresholdTriggerPeriod":3,"ThresholdTimeoutPeriod":3,"BypassesPermitted":3,"BypassDuration":15,"NlpThreshold":null,"MaxTextTriggerScanningSize":3,"UpdateChannel":"Stable","WhitelistedApplications":["TeamViewer_Servce.exe","TeamViewer_Service.exe","TeamViewer.exe","tv_w32.exe","tv_x64.exe","Telegram.exe","Slack.exe","dropbox.exe","DropboxUpdate.exe","DbxSvc.exe","Dropbox.exe","onedrive.exe","QBW32.EXE","QBDBMgr.exe","QBIDPService.exe","qbupdate.exe","QBCFMonitorService.exe","qw.exe","OUTLOOK.EXE","ONENOTE.EXE","ONENOTEM.EXE","OneDrive.exe","OfficeClickToRun.exe","MSOSYNC.EXE","LMIIgnition.exe","LMIGuardianSvc.exe","LogMeInSystray.exe","LogMeIn.exe","ryver.exe","git.exe","thunderbird.exe","mstsc.exe","WinStore.App.exe","Stardraw Design 7.exe","Stardraw Updater.exe","FedEx Web Tools.exe","MBAMWsc.exe","assistant.exe","mbamtray.exe","mbam.exe","MBAMService.exe","MbamPt.exe","Accountable2You.exe","Wunderlist.exe","MsMpEng.exe","MsSense.exe","NisSrv.exe","twist.exe","Skype.exe","SkypeHost.exe","SkypeBrowserHost.exe","EaseGuard.exe","GoogleUpdate.exe","svchost.exe","id_bglaunch.exe","id_service.exe","id_tray.exe","id_win.exe","id_idle_stat.exe","fiddler.exe","DLMSession.exe","googledrivesync.exe","GoogleUpdateSetup.exe","SugarSync.exe","WINWORD.EXE","nplastpass.exe","BoxSync.exe","Airdroid.exe","InScribe6.exe","HxOutlook.exe","HxTsr.exe","gs-server.exe","nis.exe","egui.exe","ekrn.exe","eset_nod32_antivirus_live_installer.exe","whatsapp.exe","concentr.exe","wfcrun32.exe","redirector.exe","SelfService.exe","SelfServicePlugin.exe","Receiver.exe","wfica32.exe","sync-taskbar.exe","sync-worker.exe","sihost.exe","smartscreen.exe","lync.exe","PluginHost.exe","lynchtmlconv.exe","SkypeApp.exe","JumpConnect.exe","wintac.mde","PlanSwift.exe","sh10.exe","GroundControl.exe","groundcontrolconsole.exe","atmgr.exe","EXCEL.EXE","AFMG Licence Manager.exe","ScreenConnect.WindowsClient.exe","acad.exe","WSCommCntr4.exe","AdAppMgrSvc.exe","AutodeskDesktopApp.exe","sqlservr.exe","sqlwriter.exe","sqlbrowser.exe","EaseDataBaseUpdate.exe","trello.exe","Chief Architect Premier X9.exe","QuickBooksMessaging.exe","epag.exe","EndpointService.exe","EndpointIntegration.exe","Console.exe","UpdateService.exe","Printable Postage.exe","DymoPnpService.exe","Adobe DEF Helper.exe","Adobe Desktop Service.exe","AdobeUpdateService.exe","AGSService.exe","AdobeIPCBroker.exe","readerdc_en_ka_crd_install.exe","QBWinClient.exe","AdCefWebBrowser.exe","Fusion360.exe","FusionLauncher.exe","JohnDeere Data Manager.exe","Srfeature.exe","idevsutil.exe","id_sync.exe","idwutil_600.exe","summit.exe","summitDbUpd.exe","Updater.exe","bzdoinstall.exe","bzbui.exe","bzserv.exe","bztransmit64.exe","bzfilelist.exe","MailClient.exe","adexmtsv.exe","screencast.exe","PROFILE.EXE","timecamp.exe","SourceTree.exe","pageant.exe","Sage50Accounting.exe","QBoxClient.exe","photographicdesigner.exe","bomgar-scc.exe","git-remote-https.exe","7z.exe","7za.exe","elevate.exe","Jobber.exe","QuickBooks.exe","robotaskbaricon.exe","SRServer.exe","SRManager.exe","SRFeature.exe","SRService.exe","QBIDPSerivce.exe","nbrplayer.exe","NeatImageCaptureWrapper.exe","Neat.exe","msiexec.exe"]}', `updated_at` = '2017-11-25 20:27:08' where `id` = '1';
/*==================================================*/
/* Query 4 - 2017-11-25 20:27:08 [4.28ms]  */
delete from `group_filter_assignments` where `group_id` = '1';
/*==================================================*/
/* Query 5 - 2017-11-25 20:27:08 [3.74ms]  */
select * from `groups` where `id` = '1' limit 1;
/*==================================================*/
/* Query 6 - 2017-11-25 20:27:08 [0.32ms]  */
select * from `group_filter_assignments` where `group_filter_assignments`.`group_id` = '1' and `group_filter_assignments`.`group_id` is not null;
/*==================================================*/
/* Query 7 - 2017-11-25 20:27:08 [2.03ms]  */
update `groups` set `data_sha1` = 'c66c13bc4426fadc7aeff08653692043abd2eee4', `updated_at` = '2017-11-25 20:27:08' where `id` = '1';
/*==================================================*/
/*==================================================*/
/* Query 1 - 2017-11-25 20:27:08 [1.12ms]  */
select * from `users` where `id` = '1' order by `name` asc limit 1;
/*==================================================*/
/* Query 2 - 2017-11-25 20:27:08 [0.17ms]  */
select `roles`.*, `role_user`.`user_id` as `pivot_user_id`, `role_user`.`role_id` as `pivot_role_id` from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `role_user`.`user_id` = '1';
/*==================================================*/
/* Query 3 - 2017-11-25 20:27:08 [0.35ms]  */
select * from `groups`;
/*==================================================*/
/* Query 4 - 2017-11-25 20:27:08 [1.56ms]  */
select * from `group_filter_assignments` where `group_filter_assignments`.`group_id` in ('1', '2', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19');

**Comment by dkwiebe** [comment]
As per @montesound this is still an ongoing issue.  It seems to usually happen when we upload a new list and set it to overwrite.

**Comment by dkwiebe** [comment]
@bluesven869 Could you spend some time digging into this and troubleshooting?  We're still running into this and I don't know what is causing it.

**Comment by bluesven869** [comment]
Sure. Let me check it

**Comment by bluesven869** [comment]
HI, @dkwiebe 
I have fully checked the code, and the logs.
but it seems oldest logs, so I recommed you please deploy current state to the server.

**Comment by dkwiebe** [comment]
@bluesven869 I'll work on that and get back to you.

**Comment by bluesven869** [comment]
ACTUALLY, the logic of filters list on group editor is incorrect, it's based on the filter tables.

You know filter tables may be not loaded in anytime, so I changed that with filter array variables, and it's loaded in first time & updated filters.
