### ISSUE TITLE
Add support to whitelist and blacklist sites at the user and install level.

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/FilterManager#38]
We need the option of disabling this feature when functionality is not desired. Maybe disable at the Group and User level?

Would these sites get added to the regular config file? I'm thinking ahead to a standalone version of the filter as it would also need this same functionality but would need to be editable from the app GUI rather than CitadelManager. I'm supposing that the standalone version would just have the ability to create/edit it's own config file.

**Comment by bluesven869** [comment]
Hello @montesound 
Can you post the mockup here to be understand more details?

**Comment by dkwiebe** [comment]
@montesound Can we close this?
