### ISSUE TITLE
Add support to give a user admin access to a specific group or groups.

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/FilterManager#39]
This would allow an IT person to manage policy on a group of installs.

**Comment by bluesven869** [comment]
please describe the logic for this issue.
- admin can assign the permission to the group.
- admin can see all groups, and non-admin user can see specific groups.

is that right?

**Comment by dkwiebe** [comment]
@bluesven869, I need to talk to @montesound about this.  We've been dealing with this ticket elsewhere.

**Comment by dkwiebe** [comment]
@df8Ojw This is the project we've been discussing and handling elsewhere.

it would be MOST helpful if this "Device-Requested-Deactivation* flag was simply returned as a part of each individual JSON "device" data from this existing api/URL:
>https://manage.cloudveil.org/citadel/api/manage/activations?email=amos@cloudveil.org

How difficult would it be for you to add that in? Currently for each individual device we're getting this:
>{
>    "id": 8910,
>    "user_id": 2,
>    "identifier": "2211E50C511C6C2xxxxxxxxxxxxxxxxxx",
>    "device_id": "xxxxxxxx-DESKTOP",
>    "created_at": "2018-03-21 14:14:44",
>    "updated_at": "2018-03-21 18:16:17",
>    "ip_address": "xxx.xxx.xxx.xxx",
>    "bypass_quantity": null,
>    "bypass_period": null,
>    "bypass_used": 0,
>    "token_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
>    "app_version": "1.6.24.0"
>},
It would be great if it would also include something like:
> "deactivation_requested": 1,

**Comment by dkwiebe** [comment]
@montesound Can we close this?
