### ISSUE TITLE
Reimplement GUI to manage app whitelists and blacklists

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/FilterManager#63]
We're wanting a much more powerful application listing system. It will have a list of apps which will be tagged to app_groups. The app_groups will be flagged as whitelist or blacklist. Then the app_groups will be tagged to groups. 

This is only an example.

telegram.exe is the app.

It belongs to the following app groups:
instant_messenger, ssl_bypass_required, darrens_whitelist

Here is the association to the groups that handle user settings:

User A Group:
instant_messenger
ssl_bypass_required

User B Group:
ssl_bypass_required

User C Group:
instant_messenger:

Darren Group:
instant_messenger
bypass_required
darrens_whitelist

**Comment by bluesven869** [comment]
![screenshot from 2017-12-25 18 19 29](https://user-images.githubusercontent.com/23646985/34342978-74024e86-e9a0-11e7-905b-8ef1404a1996.png)
![screenshot from 2017-12-25 18 19 42](https://user-images.githubusercontent.com/23646985/34342979-75eb793e-e9a0-11e7-84e9-9c72cd29dab7.png)

**Comment by bluesven869** [comment]
file:///home/luisantonio/Pictures/Screenshot%20from%202017-12-25%2018:19:20.png

**Comment by bluesven869** [comment]
![screenshot from 2017-12-25 18 55 19](https://user-images.githubusercontent.com/23646985/34343178-38c482da-e9a5-11e7-9edd-bd6f5f8df891.png)

**Comment by dkwiebe** [comment]
@bluesven869 This looks good.  I'll assign the ticket to myself to finish implementing applying this to the group json.

**Comment by dkwiebe** [comment]
@montesound This is live on the test server if you want to do any testing.  The way it's currently implemented means we'll need to setup the app groups but changing an item in the app group won't affect the user group until we go into the user_group settings and save them.

**Comment by montesound** [comment]
@dkwiebe Yes, that is what I'm seeing. What we really need is for it to automatically update the user_group whenever we make a change to an app_group.

**Comment by montesound** [comment]
Also notice that the Application Filtering is not cloning when we clone a user_group.

**Comment by bluesven869** [comment]
Done!

**Comment by bluesven869** [comment]
Please comment here what is needed more.

**Comment by dkwiebe** [comment]
This has been tested as in production.
