### ISSUE TITLE
Build API interface to return number of bypasses available.

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/FilterManager#65]
As per 

https://github.com/cloudveiltech/Citadel-Windows/issues/58#issuecomment-353689103

**Comment by kfreezen** [comment]
Testing on production server, and POST /me/bypass does not increment the amount of bypasses used. Is there another API for that, or is that a bug?

**Comment by dkwiebe** [comment]
@kfreezen Are you sending it just to /me/bypass or is there more to the url than that?  Try changing that to /citadel/api/v2/me/bypass.  The "/me/bypass" is relative to it's location in the config file.  I should have made that clear in the notes.

**Comment by dkwiebe** [comment]
@kfreezen You can request info on the number of bypasses available without using one by  sending "check_only" as a parameter on the post request.  It will then return a JSON array showing "used" and "available" without incrementing.

On the testing server I've also fixed the code to increment the number of bypasses used.

**Comment by dkwiebe** [comment]
For the purposes of this ticket "bypass" = "Relaxed Mode"

**Comment by kfreezen** [comment]
Yes I am using the full URL and I'm getting a good response, except that
relax policy is not decrementing. So sounds like you fixed it

**Comment by dkwiebe** [comment]
This is in place but we are missing the code to reset the count every day.

**Comment by dkwiebe** [comment]
This was coded earlier and runs daily at config('app.bypass_used_delete_time')
