### ISSUE TITLE
Change_Request Reason column broken

### ISSUE THREAD

**Issue by tysonkcv** [cloudveiltech/FilterManager#86]
Always shows: Blocked based on category: LOOKUP_UNKNOWN

![screen shot 2018-03-15 at 11 58 29 am](https://user-images.githubusercontent.com/26845997/37481823-55d6af60-2848-11e8-9da4-b30d7478a5d0.png)

**Comment by dkwiebe** [comment]
@tysonkcv This belongs on the bitbucket repo.  We can try to look there.
