### ISSUE TITLE
Improve deactivation request process

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/FilterManager#90]
On this screen it would be nice if we could just click on the toggle switch to approve or deny rather than having to open the request.

![image](https://user-images.githubusercontent.com/1034679/38286056-89c3db80-3780-11e8-9a2a-eb95f3761a69.png)

**Comment by bluesven869** [comment]
Please check it on luis-89-92 branch.
It was fixed

**Comment by dkwiebe** [comment]
This is confirmed working.
