### ISSUE TITLE
Adjust Activations Screen

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/FilterManager#91]
Please remove the identifier column from this page as we don't need it.
![image](https://user-images.githubusercontent.com/1034679/38286234-8ddb8500-3781-11e8-8674-e1ecb358fb22.png)

**Comment by bluesven869** [comment]
Hi, @dkwiebe,  
I removed identier column in this screen,

![90](https://user-images.githubusercontent.com/23646985/38471643-639400e8-3b4a-11e8-9b66-05db73d4cbb6.png)

**Comment by dkwiebe** [comment]
This is confirmed fixed.
