### ISSUE TITLE
Add Refresh Button

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/FilterManager#92]
Please add a refresh button to this screen.

![image](https://user-images.githubusercontent.com/1034679/38286539-22e0107a-3783-11e8-83b6-fc1e6f7d319d.png)

**Comment by bluesven869** [comment]
![91](https://user-images.githubusercontent.com/23646985/38471655-86cad762-3b4a-11e8-8758-fc15d490f3bf.png)

**Comment by dkwiebe** [comment]
This is working.
