### ISSUE TITLE
Need API / end-point to lookup user_id via IP address

### ISSUE THREAD

**Issue by df8Ojw** [cloudveiltech/FilterManager#95]
I need to be able to do a USER_ID lookup from a supplied IP address. This is specifically needed for our DNS query history. The only identifying information available on the DNS is the client-IP address and I need to translate that over to a USER_ID for accountability.

The IP-address might be a CV4W user or it might be a WIFI/router user ~ all I have is an IP-address. . . I need the USER_ID regardless of which filtering system they are using.

Occasionally it is possible that an IP-address could be listed for more than one of our users. The reality is that if an IP-address is located in our user-database more than once then the API / end-point should return a NULL because it isn't positively conclusive.

**Comment by df8Ojw** [comment]
I think at a minimum we should have the USER_ID and also the DEVICE_ID returned for any potential accountability alerts.

**Comment by dkwiebe** [comment]
Closing as it won't be implemented in this system.
