### ISSUE TITLE
Need API / end-point to return CV4W current version

### ISSUE THREAD

**Issue by df8Ojw** [cloudveiltech/FilterManager#96]
We need an API / end-point that will return a JSON response identifying the current CV4W **release** version number. The remote server needs to be able to query this so that it can compare it with what users actually have installed on their device(s).

**Comment by df8Ojw** [comment]
Maybe something like this:
{
    "current_verson" :  "1.6.24.0"
}

**Comment by df8Ojw** [comment]
Would it be possible to include the DATE for this version?
{
 "current_verson" : "1.6.24.0"
 "release_date" : "04/10/2018"
 }

**Comment by dkwiebe** [comment]
@bluesven869 This should be under the basic authentication portion of the api.

**Comment by bluesven869** [comment]
![version_1](https://user-images.githubusercontent.com/23646985/39298350-957dcbe0-494e-11e8-95e2-eba57dd334c1.png)
![version_2](https://user-images.githubusercontent.com/23646985/39298362-a077cf5a-494e-11e8-891a-dbc7e8452e0d.png)
![version_3](https://user-images.githubusercontent.com/23646985/39298365-a4a59cb0-494e-11e8-896c-bbd36f2b8bff.png)

**Comment by df8Ojw** [comment]
When I try to query that URL from our manage.cloudveil.org server I get this response:
$ curl "http://filtermanager.app/update/Win8.1%2064bi"
curl: (6) Could not resolve host: filtermanager.app

**Comment by bluesven869** [comment]
http://filtermanager.app is a local path in my side.

**Comment by df8Ojw** [comment]
That JSON response should do what we need to compare against when I get from the user:

_{
    "id": 8910,
    "user_id": 2,
    "identifier": "2211E50C511C6C2670D7B013CDA67A9C6C619839",
    "device_id": "AMOS-DESKTOP",
    "created_at": "2018-03-21 14:14:44",
    "updated_at": "2018-03-21 18:16:17",
    "ip_address": "209.203.162.81",
    "bypass_quantity": null,
    "bypass_period": null,
    "bypass_used": 0,
    "token_id": "cb5f7b4414f33328222733e7bc8dc537ee1f1f917e07029c0b17bf9275ed627c0a42a01e224a279b",
    "app_version": "1.6.24.0"
}_

**Comment by bluesven869** [comment]
![screenshot_14](https://user-images.githubusercontent.com/23646985/39313540-ed5fe966-497a-11e8-89ed-9bb7db0ba172.png)

**Comment by df8Ojw** [comment]
Yes, you did the right thing. Thanks!

**Comment by bluesven869** [comment]
I think this was fixed already.
