### ISSUE TITLE
Add editable fields to User's devices screen and database

### ISSUE THREAD

**Issue by df8Ojw** [cloudveiltech/FilterManager#98]
![check-in_alert_02](https://user-images.githubusercontent.com/19311569/39388515-0a09246a-4a70-11e8-8e93-93a30917f278.png)

We need 2 user-editable fields added to the device section of the "Edit User" webpage and respective database table.

Each device needs a "Check-in Days" type of text-edit field (integer values). This will be used when we scan the user devices to see how long they can go without "checking-in" before the system sends an alert. A '0' is an acceptable value as it will signify that the device will not get an alert regardless of how long it has been missing.

Also each device needs a checkbox type of entry to allow the user to opt-in / opt-out of alerting their accountability partner with any alert(s) that the system would send.

These entries can be different for each individual device that a user may have so these settings are device-specific rather than user-specific.

**Comment by dkwiebe** [comment]
@df8Ojw In https://github.com/cloudveiltech/FilterManager/issues/34 we have been adding support to report back to accountability partners.  

Do we need to control reporting by activation?  We've been planning to control it per user but we can change that if it's needed.

**Comment by df8Ojw** [comment]
@dkwiebe
This request is addressing the specifics regarding the device-hasn't-checked-in and the filter-version-is-wrong audit scans. These settings possibly would (or could) be configured somewhere else in the system but they are DEVICE specific (rather than "per user") so it seemed applicable at this location.

However we can do this as an enhancement to the over all user-experience would be the appealing route.

**Comment by bluesven869** [comment]
I have added 2 fields (check-in-days, alert-partner) in both database and UI.

![screenshot_15](https://user-images.githubusercontent.com/23646985/39697655-0b29e8fc-51c8-11e8-9f64-a65fea46f701.png)

I have one question.

Should I add those 2 fields in **App User Activations** Page?
![screenshot_16](https://user-images.githubusercontent.com/23646985/39697683-2beb28a8-51c8-11e8-8e0f-4407266d0e6d.png)
